# @baseurl=https://hotel-management-gf0g.onrender.com
# "url": "https://hotel-management-gf0g.onrender.com/"
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODFhNmQzNjJiMTdkMzVlM2ExMjJiNSIsImlhdCI6MTY4NjIxODUxMiwiZXhwIjoxNjg2MjIwMzEyfQ.AIDKYNIVmUBMR25q_JCagE72yPzfeMPASbb3SS7hnNk

@baseurl=http://localhost:3200

### Create hotel ###
###
POST {{baseurl}}/hotel/addhotel
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name":"Park residency",
    "description":"enjoy dreamy vacation",
    "location":"delhi",
    "address":"connaugt place,delhi",
    "totalRooms":20
}

### get all hotels ###
###
GET {{baseurl}}/hotel/getAllHotels

### get all hotels by location ###
###
GET {{baseurl}}/hotel/getHotelsByLocation/delhi

### hotel booking ###
###
POST {{baseurl}}/hotel/booking 
Content-Type: application/json
Authorization: bearer {{token}}

{
  "hotel":"648192a76cf498a89b97ebbe",
  "checkInDate":"4-8-2023",
  "checkOutDate":"4-9-2023",
  "numGuests":2,
  "rooms":1,
  "paymentStatus":"Paid"
}

### add hotel review ###
###
POST {{baseurl}}/hotel/review/648192a76cf498a89b97ebbe
Content-Type: application/json
Authorization: bearer {{token}}

{
      "review": "Beautiful location and friendly staff",
      "rating": 4
}


### update hotel ###
###
PATCH {{baseurl}}/hotel/update
Content-Type: application/json
Authorization: bearer {{token}}

{
      "hotelId":"648192a76cf498a89b97ebbe",
      "name":"new one hotel",
      "description":"nicer one",
      "location":"delhi",
      "address":"new delhi",
      "totalRooms":30
}


### delete hotel ###
###
DELETE {{baseurl}}/hotel/delete/648192a76cf498a89b97ebbe
Authorization: bearer {{token}}

### cancel hotel booking ###
###

POST {{baseurl}}/hotel/cancel/booking/648192ef6cf498a89b97ebc9
Content-Type: application/json
Authorization: bearer {{token}}

{
  "hotelId":"648192a76cf498a89b97ebbe"
}

### get all Bookings ###
###
GET {{baseurl}}/hotel/getAllBookings
Authorization: bearer {{token}}
