# @baseurl=https://hotelmanagement-gly8.onrender.com
@baseurl=http://localhost:3200

###
POST {{baseurl}}/user/signup
Content-Type: application/json

{
    "name":"sugreev",
    "email":"ksugreev88@gmail.com",
    "phone":8826891859,
    "role":"Admin",
    "password":"1234"
}     

###
POST {{baseurl}}/user/verify/mobile
Content-Type: application/json

{
    "phone":8826891859
}

###
POST {{baseurl}}/user/verify/mobile/otp
Content-Type: application/json

{
    "phone":8826891859,
    "otp":974348
}

###
POST {{baseurl}}/user/login
Content-Type: application/json

{
    "email":"ksugreev88@gmail.com",
    "password":"1234"
}

###
POST {{baseurl}}/user/login/token
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0N2ViM2YxNmRiZDg2NTFkZGZlMTMwMiIsImVtYWlsMSI6ImtzdWdyZWV2ODhAZ21haWwuY29tIiwiaWF0IjoxNjg2MDI1Mjg3fQ.mPEee3onDeDdoGVRa2AszJNTwImQg0YDaP8vuvw06ww

###
POST {{baseurl}}/user/logout
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0N2RkNzg4ZjgwNWI2Zjc3M2NlZjg1OSIsImVtYWlsMSI6ImhhcmRpa2dhcmc4ODVAZ21haWwuY29tIiwiaWF0IjoxNjg1OTY4OTE1fQ.Apyl71J7nbxc1CHzqSSzo0zDhKU8jGdgtzDuI2dMkKc

# hotel
###
POST {{baseurl}}/user/addhotel
Content-Type: application/json

{
    "name":"OYO",
    "description":"your dreamy destination",
    "location":"faridabad",
    "address":"old faridabad",
    "user":"647eb3f16dbd8651ddfe1302",
    "totalRooms":2
}

###
GET {{baseurl}}/user/getAllHotels

###
GET {{baseurl}}/user/getHotelsByLocation/faridabad

###
POST {{baseurl}}/user/booking
Content-Type: application/json

{
  "hotel":"647ecefc80282e93e3ab2722",
  "user":"647eb3f16dbd8651ddfe1302",
  "checkInDate":"2023-6-5",
 "checkOutDate":"2023-6-8",
  "numGuests":1,
  "rooms":1,
  "totalPrice":2000,
  "paymentStatus":"Paid"
}

###
POST {{baseurl}}/user/hotelReview/647ecefc80282e93e3ab2722/647eb3f16dbd8651ddfe1302
Content-Type: application/json

{
      "review": "Beautiful location and friendly staff",
      "rating": 4
}
