# @baseurl=https://hotel-management-gf0g.onrender.com
@baseurl=http://localhost:3200

### Create hotel ###
###
POST {{baseurl}}/hotel/addhotel
Content-Type: application/json

{
    "name":"New Murthal Residency",
    "description":"enjoy your dreamy vacation",
    "location":"delhi",
    "address":"saket,delhi",
    "user":"64801a2b632ee49ddbd7c61e",
    "totalRooms":2
}

### get all hotels ###
###
GET {{baseurl}}/hotel/getAllHotels

### get all hotels by location ###
###
GET {{baseurl}}/hotel/getHotelsByLocation/faridabad

### hotel booking ###
###
POST {{baseurl}}/hotel/booking
Content-Type: application/json

{
  "hotel":"64801a63632ee49ddbd7c627",
  "user":"64801a2b632ee49ddbd7c61e",
  "checkInDate":"4-8-2023",
  "checkOutDate":"4-9-2023",
  "numGuests":2,
  "rooms":2,
  "totalPrice":3000,
  "paymentStatus":"Paid"
}

### add hotel review ###
###
POST {{baseurl}}/hotel/review/64801a63632ee49ddbd7c627/64801a2b632ee49ddbd8c61e
Content-Type: application/json

{
      "review": "Beautiful location and friendly staff",
      "rating": 4
}

### update hotel ###
###
PATCH {{baseurl}}/hotel/update
Content-Type: application/json

{
      "hotelId":"64801a63632ee49ddbd7c627",
      "userId":"64801a2b632ee49ddbd7c61e",
      "name":"new one hotel",
      "description":"nicer one",
      "location":"delhi",
      "address":"new delhi",
      "totalRooms":20
}

### delete hotel ###
###
DELETE {{baseurl}}/hotel/delete/64801a63632ee49ddbd7c627/64801a2b632ee49ddbd7c61e

### cancel hotel booking ###
###

POST {{baseurl}}/hotel/cancel/booking/647f55d519e2b227c0f72e4f
Content-Type: application/json

{
  "hotelId":"647f54ba6bc67a97b73deb7f",
  "userId":"647f4da594a883b628444378"
}

### get all Bookings ###
###
GET {{baseurl}}/hotel/getAllBookings/64800b2cbb2de97d88d3ec08
